### ISSUE TITLE
Add support for maven multimodule project

### ISSUE THREAD

**Issue by aggroot** [creekorful/mvnparser#2]
What do you think about reading and parsing modules into a multimodule project?

**Comment by creekorful** [comment]
That would be a great functionality !

Do you want to manage the PR?

**Comment by aggroot** [comment]
sure, i'll do it

**Comment by creekorful** [comment]
Thank you! Your help is greatly appreciated 😄

**Comment by creekorful** [comment]
Hello @agalbenus, 
I was truly needing this functionality and decided to implement it.

Cheers!
